name: Build LaTeX document
on:
  push:
    branches:
      - "**/*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: minhtran_resume
          path: resume.pdf

      - name: Rename PDF file based on pushed branch
        run: |
          RELEASE_FILE_NAME="resume_${GITHUB_REF#refs/heads/}.pdf"
          mv resume.pdf "$RELEASE_FILE_NAME"
          echo "RELEASE_FILE_NAME=$RELEASE_FILE_NAME" >> $GITHUB_ENV
          
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: "${{ env.RELEASE_FILE_NAME }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
