name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: "${{ GITHUB_REF#refs/heads/ }}-latest"
      RELEASE_FILE_NAME: "resume_${{ GITHUB_REF#refs/heads/ }}.pdf"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: minhtran_resume
          path: resume.pdf

      - name: Delete existing latest tag
        run: |
          git tag -d $TAG_NAME || true
          git push origin :refs/tags/$TAG_NAME || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new latest tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: always()
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: $RELEASE_FILE_NAME
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
